name: Update Production

on:
    push:
        branches: [master]

jobs:
    update-production:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: SSH into server and deploy 
              uses: appleboy/ssh-action@v0.1.9
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script: |
                    cd cparchives
                    git pull
                    npm install
                    screen -S cparchives -X quit
                    screen -dmS cparchives
                    screen -S cparchives -X 'sudo npm run start'